name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.12.9"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 🛠️ Install system dependencies (only for Ubuntu)
      - name: Install libGLU (Linux only)
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libglu1-mesa

      - name: Install project dependencies
        run: pip install -e .

      - name: Install test dependencies
        run: pip install pytest pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=finiteelementanalysis --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
